reorg

diff --git a/scripts/validate b/scripts/validate
--- a/scripts/validate
+++ b/scripts/validate
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 set -u
 
 BOLD=$(tput bold)
@@ -20,9 +20,9 @@ echo -e "\n${BOLD}Running: go vet${NORMAL}"
 go vet ${GO_FILES} | tee /dev/stderr
 [ $? -eq 0 ] || FAILED=1 echo -e "\n${RED}Failed${NORMAL}"
 
-echo -e "\n${BOLD}Running: megacheck${NORMAL}"
-megacheck ./...
-[ $? -eq 0 ] || FAILED=1 echo -e "\n${RED}Failed${NORMAL}"
+# echo -e "\n${BOLD}Running: megacheck${NORMAL}"
+# megacheck ./...
+# [ $? -eq 0 ] || FAILED=1 echo -e "\n${RED}Failed${NORMAL}"
 
 # echo -e "\n${BOLD}Running: gocyclo${NORMAL}"
 # gocyclo -over 19 $GO_FILES
